version: 2.1
jobs:
  build_and_test:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run:
          name: Set TERM Environment Variable
          command: export TERM=dumb
      - run:
          name: Clean Build Artifacts
          command: rm -rf ~/Library/Developer/Xcode/DerivedData
      - run:
          name: Install Dependencies
          command: pod install
      - run:
          name: Set Fastlane Output Directory
          command: echo "export FL_OUTPUT_DIR=$CIRCLE_ARTIFACTS" >> $BASH_ENV
      - run:
          name: Run Fastlane
          command: fastlane test

workflows:
  build_test_workflow:
    jobs:
      - build_and_test


