jobs: 
  build_and_test:
    macos: 
      xcode: "13.3.1"
    steps: 
      - checkout
      - run: pod install
      - run: xcodebuild build-for-testing -workspace "Forecast.xcworkspace" -scheme "Forecast" -destination “platform=iOS Simulator,name=iPhone 11” 
      - run: xcodebuild test-without-building -workspace "Forecast.xcworkspace" -scheme "Forecast" -destination “platform=iOS Simulator,name=iPhone 11”
workflows:
  build_test_workflow:
    jobs: 
      build_and_test
