default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
  scan(
    scheme: "ForecastTests",
    devices: ["iPhone 14 Pro"],
      suppress_xcode_output: false,
      clean:true,
      disable_concurrent_testing: true
  )
  end
end
