default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
  run_tests(
   scheme: "ForecastTests"
   devices: ["iPhone 14 pro"]
   )
  end
end
